name: vector_drawable_from_svg
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  vector_math: ^2.0.0
  xml: ^5.3.1
  vector_drawable_core:
    path: ../vector_drawable_core
  vector_drawable_path_utils:
    path: ../vector_drawable_path_utils

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
